apply plugin: 'com.android.library'

dependencies {
    implementation 'com.android.support:support-v4:25.1.1'
    implementation 'com.madgag.spongycastle:core:1.51.0.0'
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}

android {
    compileSdkVersion 35

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            resources.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
        }

        // Move the tests to tests/java, tests/res, etc...
        androidTest.setRoot('tests')

        debug.setRoot('build-types/debug')
        release.setRoot('build-types/release')
    }

    namespace "info.guardianproject.netcipher"
}
