apply plugin: 'com.android.application'

dependencies {
    implementation project(':libraries:Jumble')
    implementation project(':libraries:NetCipher:libnetcipher')
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.palette:palette:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.core:core:1.19.0' // Or the latest version appropriate for your SDK
    implementation files('../libraries/android-async-http-1.4.6.jar')
    implementation files('../libraries/gson-2.3.1.jar')
}

def signingFile = file 'signing.gradle'
if (signingFile.exists()) apply from: 'signing.gradle'

android {
    namespace "com.terracom.qrpttbeta"
    compileSdkVersion 35
    buildToolsVersion "36.0.0"

    buildFeatures {
        buildConfig = true
    }

    defaultConfig {
        minSdkVersion 26
        targetSdkVersion 35
        applicationId "com.theofilos.chamalis.qrptt"

        versionCode 88
        versionName "1.5"
        testInstrumentationRunner "android.test.InstrumentationTestRunner"
        buildConfigField "boolean", "DONATE_NAG", "false"
    }

    flavorDimensions "default"

    productFlavors {

        official {
            dimension "default"
            applicationId "com.terracom.qrptt"
        }

        free {
            dimension "default"
            applicationId "com.theofilos.chamalis.qrptt.free"
            buildConfigField "boolean", "DONATE_NAG", "false"
        }

        jenkins {
            dimension "default"
            def env = System.getenv()
            if (env.containsKey("BUILD_NUMBER") && env.containsKey("BUILD_DISPLAY_NAME")) {
                versionCode Integer.parseInt(env.get("BUILD_NUMBER"))
                versionName env.get("BUILD_DISPLAY_NAME")
            } else {
                versionCode 0
                versionName "Unknown Nightly"
            }
            applicationId "com.theofilos.chamalis.qrptt.jenkins"
        }
    }

    lintOptions {
        abortOnError false
    }
}
