apply plugin: 'com.android.application'

dependencies {
    implementation project(':libraries:Jumble')
    implementation project(':libraries:NetCipher:libnetcipher')
    implementation 'com.android.support:support-v4:28.0.0'
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:cardview-v7:28.0.0'
    implementation 'com.android.support:palette-v7:28.0.0'
    implementation 'com.android.support:recyclerview-v7:28.0.0'
    implementation files('../libraries/android-async-http-1.4.6.jar')
    implementation files('../libraries/gson-2.3.1.jar')
}

def signingFile = file 'signing.gradle';
if (signingFile.exists()) apply from: 'signing.gradle'

android {
    namespace "com.terracom.qrpttbeta"
    compileSdkVersion 35
    buildToolsVersion "36.0.0"

    buildFeatures {
        buildConfig = true
    }

    defaultConfig {
        minSdkVersion 26
        targetSdkVersion 35
        applicationId "com.theofilos.chamalis.qrptt"

        versionCode 88
        versionName "1.5"
        testInstrumentationRunner "android.test.InstrumentationTestRunner"
        buildConfigField "boolean", "DONATE_NAG", "false"
    }

    flavorDimensions "default"

    productFlavors {

        official {
            dimension "default"
            applicationId "com.terracom.qrptt"
        }

        free {
            dimension "default"
            applicationId "com.theofilos.chamalis.qrptt.free"
            buildConfigField "boolean", "DONATE_NAG", "false"
        }

        jenkins {
            dimension "default"
            def env = System.getenv()
            if (env.containsKey("BUILD_NUMBER") && env.containsKey("BUILD_DISPLAY_NAME")) {
                versionCode Integer.parseInt(env.get("BUILD_NUMBER"))
                versionName env.get("BUILD_DISPLAY_NAME")
            } else {
                versionCode 0
                versionName "Unknown Nightly"
            }
            applicationId "com.theofilos.chamalis.qrptt.jenkins"
        }
    }

    lintOptions {
        abortOnError false
    }
}
